# Generated by Django 6.0.5 on 2026-05-15 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('show_type', models.CharField(choices=[('MOVIE', 'Movie'), ('ANIME', 'Anime')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffilliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate', to='catalog.show')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.streamingplatform')),
            ],
        ),
    ]
