# Generated by Django 6.0.5 on 2026-05-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='affiliate_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
